### ISSUE TITLE
Environment variable with false value isn't picked up correctly

### ISSUE THREAD

**Issue by dsager** [monkeylearn/monkeylearn-ruby#20]
The Gem doesn't read the environment variable `MONKEYLEARN_RETRY_IF_THROTTLE` properly.
When setting it to `false` or any other falsey value like `0` or `off`, the gem considers this to be true.

The issue seems to be in `Monkeylearn::Defaults.retry_if_throttle`, which does the following:
```ruby
ENV['MONKEYLEARN_RETRY_IF_THROTTLE'] || RETRY_IF_THROTTLE
``` 

All environment variables are string values, which always evaluate to `true` in ruby. Even if it would be evaluated as `false`, the `||` would basically ignore it and set it to `RETRY_IF_THROTTLE`, which is `true`...

### How to reproduce
```
[1] pry(main)> ENV.key?('MONKEYLEARN_RETRY_IF_THROTTLE')
=> true
[2] pry(main)> ENV['MONKEYLEARN_RETRY_IF_THROTTLE']        
=> "false"
[3] pry(main)> (Monkeylearn.retry_if_throttle ? 'retry!' : 'no retry!')         
=> "retry!"
```

### Workaround
If you're using Rails, this works:
```ruby
Monkeylearn.configure do |c| 
  c.retry_if_throttle = ActiveModel::Type::Boolean.new.cast(
    ENV['MONKEYLEARN_RETRY_IF_THROTTLE']
  )
end
```
If you're not using Rails, something like this works:
```ruby
Monkeylearn.configure do |c| 
  c.retry_if_throttle =
    !ENV['MONKEYLEARN_RETRY_IF_THROTTLE']
      .to_s
      .downcase
      .in?(%w[0 f false off])
end
```

**Comment by omab** [comment]
Thanks for the report @dsager, the team will look into this soon.
