### ISSUE TITLE
Allow `upload_samples` to receive Category Names like CSV upload

### ISSUE THREAD

**Issue by harlow** [monkeylearn/monkeylearn-ruby#4]
The CSV upload is very nice to work with because we can just use the category path instead of having to know the IDs. It's also very nice that it dynamically creates the categories.

How does team feel about support for similar upload?

```
samples = [
    ['Nice beatiful', 'Ratings/Positive'],
    ['awesome excelent', 'Ratings/Positive'],
    ['Awful bad', 'Ratings/Negative'],
    ['sad pale', 'Ratings/Negative'],
    ['happy sad both multilabel', ['Ratings/Positive', 'Ratings/Negative']]
]
r = Monkeylearn.classifiers.upload_samples(classifier_id, samples)
```

**Comment by gonz** [comment]
Hey @harlow this is currently on the roadmap for the Monkeylearn API, along with tagging support. We'll add it to the lib as soon as it's supported there. Thanks!
