### ISSUE TITLE
The input texts is missing: This is the list of texts

### ISSUE THREAD

**Issue by MaxPleaner** [monkeylearn/monkeylearn-ruby#5]
I'm using the following code:

```ruby
            data = {
              input: [
                { text: "a sentence" }
              ]
            }            
            response = Monkeylearn.pipelines.run(
                'pi_s5izXXhC',
                data,
                sandbox: false
            )
```

I have previously set up the client with my API key.

My response is 

```ruby
     body=
      "{\"status_code\": 422, \"detail\": \"The input texts is missing: This is the list of texts.\"}",
```

Not sure how to fix this, as I got the example off the README.

I was able to make a "classifer" example work, but when I tried to use a pipeline, this error occurred.

See my working "classifer" attempt:

```ruby
            response = Monkeylearn.classifiers.classify(
                'cl_4PFzSWVR', 
                [text],
                sandbox: false
            )
 ```

**Comment by gonz** [comment]
@MaxPleaner Note that pipelines are very flexible and they can take different inputs depending on what each pipeline in meant to do, the public pipeline you are using takes an input like the following:
```
{
  "texts": [
    {
      "text": "text1"
    },
    {
      "text": "text2"
    }
  ]
}
```
The pipelines that follow best practices usually have the `input_example` metadata which is used to test a pipeline in the UI, you can get an example of a correct input there (click the json tab in the Test API form of the pipeline detail).

Theres not much this lib can do at the moment to give a more friendly error message but some improvements will be implemente in the monkeylearn API to fix this soon.

**Comment by MaxPleaner** [comment]
Thank you, good explanation and I understand now. I thought the pipelines
came with the sample data "packed in" them and that when I made the API
request, the same data was loaded as in the UI.

I suppose I was confused because the data did seem to be autoloaded when I
was using a classifier. I expected the same thing to happen with the
pipeline.
