### ISSUE TITLE
The List Classifiers endpoint is not working

### ISSUE THREAD

**Issue by JamesChevalier** [monkeylearn/monkeylearn-ruby#7]
The [API Reference](http://docs.monkeylearn.com/article/api-reference/#List_ClassifiersGET) documents a List Classifiers endpoint, and the API tab in my Classifier page displays that the List Classifiers endpoint should be called with `Monkeylearn.classifiers.list()`.

When I try this in a Rails console, though, I get this error:

> NoMethodError: undefined method `list' for Monkeylearn::Classifiers:Module

In the meantime, I can manually find my Classifier's ID in its URL (rather than collecting it from the `list` response).

Thanks for building such a great experience & documenting everything so well. This is the only hiccup I've hit, and it's not critical.

**Comment by gonz** [comment]
I'm closing this since it's fixed in the current release. Thanks for contributing and sorry we took this long to get back to you!
