### ISSUE TITLE
NoMethodError: undefined method `body' for Monkeylearn::Response

### ISSUE THREAD

**Issue by mmplisskin** [monkeylearn/monkeylearn-ruby#8]
```NoMethodError: undefined method `body' for #<Monkeylearn::Response:0x007fa32c6434e0>
from .../.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/monkeylearn-0.2.2/lib/monkeylearn/response.rb:11:in `raw_response=```

I seem to be getting this exception frequently at multiple endpoints i.e
```Monkeylearn.classifiers.train(my_classifier_id)```

**Comment by gonz** [comment]
Hey @mmplisskin I'm closing this since it should be fixed in the current release. Thanks for contributing and sorry we took this long to get back to you!
